### PR TITLE
Fix isjQuery util to match $-prefixed properties

### LINKED ISSUE #42: isjQuery util doesn't work for properties of non-jQuery objects
`isjQuery` detects the following as jQuery expressions:
* `$('div').find('p').first()`
* `$div.find('p').first()`

but not

* `this.$div.find('p').first()`

which is a pretty common occurrence

### PR DESCRIPTION
**Pull request by edg2s**
Fixes #42

### CODE REVIEW

File: rules/utils.js [hunk 1]
```diff
@@ -1,18 +1,19 @@
 'use strict'
 
-function traverse(node) {
+function traverse(node, test) {
```
Comment (Krinkle) [inline rules/utils.js]: Neat!
